on: push
jobs:
  qa:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.2
      - name: Install prerequisites
        run: |
          python -m pip install -q -U pip
          python -m pip install -q -r requirements.txt
      - name: Run tests
        run: |
          python run_tests.py
